# Site settings
title: Harun Urhan | Blog
description: "Blog of a student who likes big data and other stuff too"
url: "http://harunurhan.github.io"
author:
  name: "Harun Urhan"
  email: "harunurhan17@gmail.com"
  url: "http://harunurhan.github.io"

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "0.0.1"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
